import React, { useMemo } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { colors, radius, spacing, typography } from '../../../theme';
import { useWeeklySummary } from '../../analytics/hooks/useWeeklySummary';
import { useDailyHistory } from '../../daily-log/hooks/useDailyHistory';

export function InsightsScreen() { const weekStart = useMemo(() => { const date = new Date(); date.setDate(date.getDate() - date.getDay() + 1); return date.toISOString().slice(0, 10); }, []); const today = new Date().toISOString().slice(0, 10); const weekly = useWeeklySummary(weekStart); const history = useDailyHistory(weekStart, today); const days = weekly.data?.days ?? []; const average = days.length ? days.reduce((sum, item) => sum + item.calories, 0) / days.length : 0; const maxCalories = Math.max(...days.map((item) => item.calories), 1); return <View style={styles.page}><Text style={styles.eyebrow}>İÇGÖRÜLER</Text><Text style={styles.title}>Haftalık özet</Text><View style={styles.card}><Text style={styles.cardLabel}>ORTALAMA KALORİ</Text><Text style={styles.value}>{Math.round(average)} kcal</Text><Text style={styles.muted}>Bu hafta günlük kayıtlarına göre.</Text></View><View style={styles.card}><Text style={styles.cardTitle}>Kalori grafiği</Text><View style={styles.chart}>{days.map((day) => <View key={day.date} style={styles.barColumn}><Text style={styles.barValue}>{Math.round(day.calories)}</Text><View style={styles.barTrack}><View style={[styles.bar, { height: `${Math.max((day.calories / maxCalories) * 100, 4)}%` }]} /></View><Text style={styles.day}>{day.date.slice(8, 10)}</Text></View>)}</View></View><View style={styles.card}><Text style={styles.cardTitle}>Günlük geçmiş</Text>{(history.data ?? []).map((day) => <View key={day.id} style={styles.historyRow}><Text style={styles.historyDate}>{day.logDate}</Text><Text style={styles.historyValue}>{Math.round(day.totalCalories)} kcal · {Math.round(day.waterConsumedMilliliters)} ml su</Text></View>)}{!history.isLoading && (history.data ?? []).length === 0 ? <Text style={styles.muted}>Bu hafta henüz kayıt yok.</Text> : null}</View><View style={styles.card}><Text style={styles.cardTitle}>Makrolar</Text><Text style={styles.muted}>Protein, karbonhidrat ve yağ değerleri günlük özetlerle birlikte takip ediliyor.</Text></View></View>; }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background, padding: spacing.lg, paddingTop: spacing.xl }, eyebrow: { ...typography.label, color: colors.coral, letterSpacing: 1.4 }, title: { ...typography.title, color: colors.text, marginTop: 4 }, card: { backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.lg, marginTop: spacing.lg }, cardLabel: { ...typography.label, color: colors.textMuted, letterSpacing: 1 }, value: { ...typography.display, color: colors.ink, marginTop: spacing.sm }, cardTitle: { ...typography.heading, color: colors.text }, muted: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm }, chart: { height: 180, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-around', marginTop: spacing.lg }, barColumn: { flex: 1, height: '100%', alignItems: 'center', justifyContent: 'flex-end' }, barValue: { ...typography.label, color: colors.textMuted, fontSize: 10, marginBottom: 4 }, barTrack: { height: 125, width: 22, justifyContent: 'flex-end', backgroundColor: colors.surfaceMuted, borderRadius: radius.pill, overflow: 'hidden' }, bar: { width: '100%', backgroundColor: colors.coral, borderRadius: radius.pill }, day: { ...typography.label, color: colors.textMuted, fontSize: 11, marginTop: 6 }, historyRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.sm, borderBottomWidth: 1, borderBottomColor: colors.border }, historyDate: { ...typography.body, color: colors.text }, historyValue: { ...typography.label, color: colors.coral, fontSize: 11 } });
