const runtimeConfig = window.EATWELL_CONFIG || {};
const API_BASE_URL = runtimeConfig.apiBaseUrl || '{API_BASE_URL}';
const firebaseState = { app: null, auth: null, loaded: false };
const API = {
  dailyLogs: '/api/daily-logs', summary: '/api/daily-logs/summary', history: '/api/daily-logs/history',
  logItems: '/api/daily-logs/items', water: '/api/daily-logs/water', searchFoods: '/api/foods/search', barcode: '/api/foods/barcode',
  analyzeImage: '/api/foods/analyze-image', favoriteFoods: '/api/foods/favorites', recentFoods: '/api/foods/recent',
  generateRecipe: '/api/recipes/generate', savedRecipes: '/api/recipes/saved', profile: '/api/profile', allergens: '/api/profile/allergens',
  nutritionGoals: '/api/nutrition-goals', weeklySummary: '/api/analytics/weekly-summary', health: '/api/health'
};

const state = { tab: 'home', date: new Date(), water: 1250, favorite: false, foods: [
  { id: 1, meal: 'Kahvaltı', name: 'Yulaflı yoğurt kasesi', emoji: '🥣', qty: '250 g', kcal: 310, protein: 18 },
  { id: 2, meal: 'Öğle', name: 'Izgara tavuklu salata', emoji: '🥗', qty: '380 g', kcal: 520, protein: 42 },
  { id: 3, meal: 'Atıştırmalık', name: 'Elma & badem', emoji: '🍎', qty: '1 porsiyon', kcal: 180, protein: 5 }
]};
const meals = ['Kahvaltı', 'Öğle', 'Akşam', 'Atıştırmalık'];
const fmt = n => new Intl.NumberFormat('tr-TR').format(n);
const dateText = d => new Intl.DateTimeFormat('tr-TR', { day: 'numeric', month: 'long', weekday: 'long' }).format(d);
const apiDate = d => d.toISOString().slice(0, 10);

async function loadFirebase() {
  if (firebaseState.loaded) return firebaseState.auth;
  const cfg = runtimeConfig.firebase || {};
  if (!cfg.apiKey || !cfg.projectId || !cfg.appId) return null;
  const [{ initializeApp }, authModule] = await Promise.all([
    import('https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js'),
    import('https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js')
  ]);
  firebaseState.app = initializeApp(cfg);
  firebaseState.auth = authModule.getAuth(firebaseState.app);
  firebaseState.loaded = true;
  return firebaseState.auth;
}

async function apiFetch(path, options = {}) {
  const headers = new Headers(options.headers || {});
  headers.set('Content-Type', 'application/json');
  const auth = await loadFirebase();
  const token = auth?.currentUser ? await auth.currentUser.getIdToken() : null;
  if (token) headers.set('Authorization', `Bearer ${token}`);
  const response = await fetch(`${API_BASE_URL}${path}`, { ...options, headers });
  if (response.status === 401) { toast('Oturumun sona erdi, lütfen tekrar giriş yap.'); authModal(); }
  if (response.status === 429) toast('Çok fazla istek gönderildi, lütfen biraz bekleyin.');
  if (response.status >= 500) toast('Bir sorun oluştu. Lütfen tekrar dene.');
  return response;
}

const backendConfigured = () => Boolean(API_BASE_URL && !API_BASE_URL.includes('{') && !API_BASE_URL.includes('your-api-host'));
async function mutateRemote(path, method, body) {
  if (!backendConfigured()) return false;
  try { const response = await apiFetch(path, { method, body: JSON.stringify(body) }); return response.ok; }
  catch { toast('Sunucuya ulaşılamadı; demo görünümü korunuyor.'); return false; }
}

function render() {
  document.querySelectorAll('.nav-item').forEach(b => b.classList.toggle('active', b.dataset.tab === state.tab));
  const views = { home: homeView, log: logView, recipes: recipesView, analytics: analyticsView, profile: profileView };
  document.querySelector('#app-content').innerHTML = views[state.tab]();
  bind();
}
function homeView() { return `<div class="eyebrow">${dateText(state.date)}</div><h1 class="page-title">Merhaba, Melih!</h1><div class="date-row"><span class="date-label">Bugünün tabağı</span><div class="date-arrows"><button data-action="prev-day">‹</button><button data-action="next-day">›</button></div></div>
  <section class="hero-card"><span class="hero-kicker">Günlük kalori pusulası</span><div class="gauge-wrap"><div class="gauge"><div class="gauge-value"><strong>1.010</strong><span>/ 1.600 kcal</span></div></div><div><span class="sticker">✦ Hedefe yakın</span><p style="margin-top:13px;font-size:13px;line-height:1.4;max-width:145px">Bugün ritmin çok iyi. Akşam için <b>590 kcal</b> alanın var.</p></div></div><div class="hero-stats"><div class="hero-stat"><span>Tüketilen</span><strong>1.010</strong></div><div class="hero-stat"><span>Kalan</span><strong>590</strong></div><div class="hero-stat"><span>Oran</span><strong>%63</strong></div></div></section>
  <div class="section-head"><h2>Makroların</h2><button data-tab-link="analytics">Detaylı analiz →</button></div><div class="macro-grid"><div class="macro-card protein"><span class="macro-label">Protein</span><strong>65 / 120g</strong><div class="mini-track"><i style="width:54%"></i></div></div><div class="macro-card carb"><span class="macro-label">Karbonhidrat</span><strong>110 / 180g</strong><div class="mini-track"><i style="width:61%"></i></div></div><div class="macro-card fat"><span class="macro-label">Yağ</span><strong>32 / 55g</strong><div class="mini-track"><i style="width:58%"></i></div></div></div>
  <div class="section-head"><h2>Su sayacı</h2><span class="sticker teal">5 / 8 bardak</span></div><div class="water-card"><div class="water-icon">💧</div><div><strong>${fmt(state.water)} ml</strong><p>Günlük hedefin 2.000 ml</p></div><button data-action="add-water">+</button></div>
  <div class="section-head"><h2>Hızlı ekle</h2></div><div class="quick-grid"><button class="quick-action" data-action="barcode"><span>▣</span><div>Barkod Tara<small>Ürünü okut</small></div></button><button class="quick-action" data-action="image"><span>◉</span><div>Fotoğrafla<small>AI ile analiz et</small></div></button><button class="quick-action" data-action="search"><span>⌕</span><div>Besin Ara<small>Veritabanında bul</small></div></button><button class="quick-action" data-action="recipe"><span>♨</span><div>Tarif Oluştur<small>Malzemelerini yaz</small></div></button></div>
  <div class="section-head"><h2>Bugünden notlar</h2><button data-tab-link="log">Tümünü gör →</button></div><div class="warning"><span style="font-size:24px">!</span><div><strong>Alerjen uyarısı</strong><p>Profilindeki <b>süt</b> kısıtı nedeniyle yoğurt kasesini kontrol et.</p></div></div>
  <div class="section-head"><h2>Son eklenenler</h2></div><div>${state.foods.map(foodRow).join('')}</div>` }
function foodRow(f) { return `<div class="food-row"><div class="food-emoji">${f.emoji}</div><div class="food-info"><strong>${f.name}</strong><span>${f.qty} · ${f.meal}</span></div><span class="food-cal">${f.kcal} kcal</span></div>` }
function logView() { return `<div class="eyebrow">Günlük takip</div><h1 class="page-title">Tabağını kur.</h1><div class="date-row"><span class="date-label">${dateText(state.date)}</span><div class="date-arrows"><button data-action="prev-day">‹</button><button data-action="next-day">›</button></div></div><div class="chart-card"><div style="display:flex;justify-content:space-between;align-items:end"><div><span class="eyebrow">Günlük toplam</span><h2 style="font-family:'DM Sans';font-size:29px;margin-top:3px">1.010 <small style="font-size:13px;font-weight:500">/ 1.600 kcal</small></h2></div><span class="sticker">%63</span></div></div>${meals.map(meal => `<section class="meal-card"><div class="meal-head"><h3>${meal}</h3><button class="add-mini" data-action="add-food" data-meal="${meal}">+</button></div>${state.foods.filter(f=>f.meal===meal).map(f=>`<div class="log-item"><div class="food-emoji">${f.emoji}</div><div class="food-info"><strong>${f.name}</strong><span class="qty">${f.qty} · ${f.kcal} kcal · ${f.protein}g protein</span></div><button class="delete-btn" data-action="delete-food" data-id="${f.id}" aria-label="Sil">×</button></div>`).join('') || `<div class="meal-empty">Bu öğünde henüz bir şey yok. Tabağına ilk lokmayı ekle.</div>`}</section>`).join('')}<div class="section-head"><h2>Su kaydı</h2><button class="text-button" data-action="add-water">+ 250 ml ekle</button></div><div class="water-card"><div class="water-icon">💧</div><div><strong>${fmt(state.water)} ml</strong><p>Bugün içilen su</p></div><span class="sticker teal">%62</span></div>` }
function recipesView() { return `<div class="eyebrow">Retro mutfak</div><h1 class="page-title">Tarif defteri.</h1><p style="margin:12px 0 20px;color:rgba(43,33,28,.68);font-size:14px;line-height:1.45">Elindeki malzemeleri söyle, sana hedeflerine uygun yeni bir tabak kuralım.</p><button class="primary-btn" data-action="recipe">✦ Yeni tarif oluştur</button><div class="section-head"><h2>Kaydedilen tarifler</h2><span class="sticker coral">2 tarif</span></div><div class="recipe-card"><span class="sticker teal">Favori</span><h3 style="margin-top:12px">İsli nohutlu shakshuka</h3><p>Domates, yumurta ve nohutun tek tavada buluştuğu, protein dolu renkli bir akşam.</p><div class="recipe-meta"><span>⏱ 25 dk</span><span>♨ 420 kcal</span><span>👤 2 pors.</span></div></div><div class="recipe-card"><span class="sticker">Yeni tarif</span><h3 style="margin-top:12px">Bademli elmalı yulaf</h3><p>Kahvaltıya hızlı, tarçınlı ve çıtır bir başlangıç.</p><div class="recipe-meta"><span>⏱ 12 dk</span><span>♨ 310 kcal</span><span>👤 1 pors.</span></div></div>` }
function analyticsView() { return `<div class="eyebrow">Haftalık bakış</div><h1 class="page-title">Ritmini gör.</h1><div class="date-row"><span class="date-label">16 — 22 Eylül 2026</span><button class="secondary-btn" style="padding:8px 11px;font-size:12px" data-action="date-range">Bu hafta⌄</button></div><div class="chart-card"><h3>Kalori günlüğü</h3><div class="bars">${[['Pzt',61],['Sal',76],['Çar',45],['Per',68],['Cum',84],['Cmt',55],['Paz',63]].map((x,i)=>`<div class="bar ${i===6?'today':''}"><i style="height:${x[1]}%"></i><span>${x[0]}</span></div>`).join('')}</div><div style="display:flex;justify-content:space-between;margin-top:12px;font-size:12px;color:rgba(43,33,28,.6)"><span>Hedef: 1.600 kcal</span><span>Ort. 1.420 kcal</span></div></div><div class="analytics-stats"><div class="stat-card"><span>Ortalama</span><strong>1.420</strong><small>kcal / gün</small></div><div class="stat-card"><span>Hedefe uyum</span><strong>%88</strong><small>son 7 gün</small></div></div><div class="section-head"><h2>Makro trendi</h2><span class="sticker teal">İyi gidiyor</span></div><div class="chart-card"><div style="display:grid;gap:14px"><div><div style="display:flex;justify-content:space-between;font-size:13px;font-weight:800"><span>Protein</span><span>65g ort.</span></div><div class="mini-track" style="height:10px;margin-top:7px"><i style="width:72%;background:var(--orange)"></i></div></div><div><div style="display:flex;justify-content:space-between;font-size:13px;font-weight:800"><span>Karbonhidrat</span><span>164g ort.</span></div><div class="mini-track" style="height:10px;margin-top:7px"><i style="width:61%;background:var(--teal)"></i></div></div><div><div style="display:flex;justify-content:space-between;font-size:13px;font-weight:800"><span>Yağ</span><span>49g ort.</span></div><div class="mini-track" style="height:10px;margin-top:7px"><i style="width:58%;background:var(--coral)"></i></div></div></div></div>` }
function profileView() { return `<div class="eyebrow">Beslenme pasaportu</div><h1 class="page-title">Kendin için.</h1><div class="profile-card" style="margin-top:18px"><div class="profile-avatar">M</div><div><h2>Melih Esen</h2><p>Hedef: dengeli beslenme · 75 kg</p></div><span style="margin-left:auto;font-size:25px">✦</span></div><div class="section-head"><h2>Kısayollar</h2></div><div class="profile-menu"><button class="menu-row" data-action="auth"><span class="menu-icon">↳</span><div><strong>Firebase oturumu</strong><span>Giriş yap veya hesabını bağla</span></div><b>›</b></button><button class="menu-row" data-action="edit-profile"><span class="menu-icon">✎</span><div><strong>Profil bilgileri</strong><span>Kilo, boy, doğum tarihi</span></div><b>›</b></button><button class="menu-row" data-action="allergens"><span class="menu-icon">!</span><div><strong>Alerjenlerim</strong><span>Süt, yer fıstığı</span></div><b>›</b></button><button class="menu-row" data-action="goal"><span class="menu-icon">◎</span><div><strong>Beslenme hedefim</strong><span>1.600 kcal · 120g protein</span></div><b>›</b></button><button class="menu-row" data-action="favorites"><span class="menu-icon">♡</span><div><strong>Favorilerim</strong><span>Kaydettiğin besin ve tarifler</span></div><b>›</b></button></div><button class="text-button" style="display:block;margin:26px auto;color:var(--plum)" data-action="logout">Çıkış yap</button>` }

function modal(title, body) { document.querySelector('#modal-root').innerHTML = `<div class="modal-backdrop" data-action="close-modal"><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h2>${title}</h2><button class="close-btn" data-action="close-modal">×</button></div>${body}</div></div>`; bind(); }
function bind() { document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render()}); document.querySelectorAll('[data-tab-link]').forEach(b=>b.onclick=()=>{state.tab=b.dataset.tabLink;render()}); document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action,b.dataset)); }
function action(type, data={}) { if(type==='prev-day'){state.date.setDate(state.date.getDate()-1);render()} if(type==='next-day'){state.date.setDate(state.date.getDate()+1);render()} if(type==='profile'){state.tab='profile';render()} if(type==='auth'){authModal()} if(type==='add-water'){mutateRemote(API.water,'POST',{milliliters:250,logDate:apiDate(state.date)}).then(ok=>{state.water+=250;toast(ok?'250 ml su eklendi ve kaydedildi 💧':'250 ml su eklendi (demo) 💧');render()})} if(type==='delete-food'){if(confirm('Bu kaydı silmek istediğine emin misin?')){mutateRemote(`${API.logItems}/${data.id}`,'DELETE').then(()=>{state.foods=state.foods.filter(f=>String(f.id)!==String(data.id));toast('Kayıt silindi');render()})}} if(type==='close-modal'){document.querySelector('#modal-root').innerHTML=''} if(type==='search'||type==='add-food'){foodModal(data.meal||'Öğle')} if(type==='add-demo-food'){const meal=data.meal||'Öğle'; const draft={id:Date.now(),meal,name:'Yulaflı meyve kasesi',emoji:'🥣',qty:'250 g',kcal:310,protein:18}; mutateRemote(API.logItems,'POST',{foodExternalId:'demo-oat-bowl',foodName:draft.name,quantityGrams:250,mealType:meal==='Kahvaltı'?'breakfast':meal==='Öğle'?'lunch':meal==='Akşam'?'dinner':'snack',logDate:apiDate(state.date),caloriesPer100Grams:124,proteinPer100Grams:7.2,carbohydratesPer100Grams:16.8,fatPer100Grams:3.6,brand:null,barcode:null}).then(ok=>{state.foods.push(draft);document.querySelector('#modal-root').innerHTML='';toast(ok?'Besin günlüğe eklendi ve kaydedildi':'Besin günlüğe eklendi (demo)');render()})} if(type==='barcode'){barcodeModal()} if(type==='image'){imageModal()} if(type==='recipe'){recipeModal()} if(type==='edit-profile'){profileModal()} if(type==='allergens'){allergenModal()} if(type==='goal'){goalModal()} if(type==='favorites'){toast('Favoriler yakında burada görünecek')} if(type==='logout'){toast('Demo oturumundan çıkıldı')} if(type==='notifications'){toast('Bugün için yeni bildirim yok')} }
function authModal(){modal('Firebase ile giriş',`<p style="font-size:13px;line-height:1.45;color:rgba(43,33,28,.7)">EatWell hesabın Firebase Authentication ile korunur. Şifre bilgilerin EatWell backend'ine gönderilmez.</p><div class="field"><label>E-posta</label><input id="auth-email" type="email" placeholder="sen@ornek.com"></div><div class="field"><label>Şifre</label><input id="auth-password" type="password" placeholder="••••••••"></div><button class="primary-btn" data-action="firebase-login">Giriş yap</button><button class="secondary-btn" style="width:100%;margin-top:10px" data-action="firebase-register">Yeni hesap oluştur</button><button class="text-button" style="display:block;margin:16px auto 0" data-action="firebase-reset">Şifremi unuttum</button><p style="font-size:11px;margin-top:15px;color:rgba(43,33,28,.55)">Firebase bilgileri config.js içinde doldurulmadıysa bu ekran demo modunda kalır.</p>`)}
function foodModal(meal='Öğle'){modal('Besin ekle',`<div class="field"><label>Besin ara</label><input id="food-search" placeholder="örn. yoğurt, muz, tavuk" autofocus></div><div class="food-row" style="background:var(--mustard);margin:10px 0;border:2px solid var(--espresso);border-radius:13px;padding:10px"><div class="food-emoji">🍌</div><div class="food-info"><strong>Muz</strong><span>89 kcal / 100 g · karbonhidrat 23g</span></div><button class="secondary-btn" data-action="add-demo-food" data-meal="${meal}">Ekle</button></div><div class="food-row"><div class="food-emoji">🥛</div><div class="food-info"><strong>Süzme yoğurt</strong><span>73 kcal / 100 g · protein 10g</span></div><button class="secondary-btn" data-action="add-demo-food" data-meal="${meal}">Ekle</button></div><p style="font-size:12px;color:rgba(43,33,28,.6);margin-top:15px">Arama, gerçek bağlantıda <code>GET /api/foods/search</code> ile çalışacak.</p>`);document.querySelectorAll('[data-action="add-demo-food"]').forEach(b=>b.onclick=()=>{state.foods.push({id:Date.now(),meal:b.dataset.meal,name:'Muz',emoji:'🍌',qty:'100 g',kcal:89,protein:1});document.querySelector('#modal-root').innerHTML='';toast('Muz günlüğe eklendi');render()})}
function barcodeModal(){modal('Barkod tara',`<div style="height:190px;background:var(--espresso);border:3px solid var(--orange);border-radius:16px;display:grid;place-items:center;color:var(--cream);font-size:50px;position:relative"><span>▣</span><div style="position:absolute;left:25px;right:25px;height:2px;background:var(--coral);box-shadow:0 0 12px var(--coral)"></div></div><p style="text-align:center;margin:14px 0;color:rgba(43,33,28,.7);font-size:13px">Ürünün barkodunu çerçeveye hizala.</p><div class="field"><label>Manuel barkod</label><input placeholder="8690000000000"></div><button class="primary-btn" data-action="scan-result">Ürünü bul</button>`);}
function imageModal(){modal('Fotoğrafla analiz et',`<div style="border:2px dashed var(--espresso);border-radius:16px;padding:30px;text-align:center;background:var(--paper)"><div style="font-size:42px">📸</div><h3 style="margin:10px 0">Tabağını göster</h3><p style="font-size:13px;color:rgba(43,33,28,.65)">Fotoğrafı yükle, AI tahmini besin değerlerini çıkarsın.</p></div><button class="primary-btn" style="margin-top:15px" data-action="analyze-result">Demo fotoğrafını analiz et</button>`);}
function recipeModal(){modal('Yeni tarif oluştur',`<div class="field"><label>Malzemeler</label><input id="ingredients" value="yumurta, domates, ıspanak" /></div><div class="field"><label>Beslenme tercihi</label><select><option>Yüksek protein</option><option>Dengeli</option><option>Vejetaryen</option></select></div><div class="field"><label>Porsiyon</label><div class="chips"><button class="chip active">2 porsiyon</button><button class="chip">4 porsiyon</button></div></div><button class="primary-btn" data-action="generate-result">✦ Tarifi oluştur</button><p style="font-size:12px;margin-top:13px;color:rgba(43,33,28,.6)">AI önerileri backend'deki <code>POST /api/recipes/generate</code> endpoint'ine bağlanacak.</p>`);}
function profileModal(){modal('Profil bilgileri',`<div class="field"><label>Görünen ad</label><input id="profile-name" value="Melih Esen" /></div><div class="field"><label>Kilo (kg)</label><input id="profile-weight" value="75" type="number" /></div><div class="field"><label>Boy (cm)</label><input id="profile-height" value="180" type="number" /></div><button class="primary-btn" data-action="save-profile">Değişiklikleri kaydet</button>`)}
function allergenModal(){modal('Alerjenlerim',`<p style="font-size:13px;line-height:1.4;margin-bottom:15px">Eşleşmeler, ürün verisi mevcut olduğunda gösterilir. Şüpheli ürünlerde etiketi kontrol etmeyi unutma.</p><div class="chips">${['Süt','Yer fıstığı','Gluten','Yumurta','Soya','Kabuklu deniz ürünleri'].map((x,i)=>`<button class="chip ${i<2?'active':''}">${x}</button>`).join('')}</div><button class="primary-btn" style="margin-top:20px" data-action="save-allergens">Alerjenleri kaydet</button>`)}
function goalModal(){modal('Beslenme hedefim',`<div class="warning" style="margin-bottom:15px"><span>✦</span><div><strong>AI önerisi</strong><p>Hedefin ve aktivite düzeyine göre önerilen değerler.</p></div></div><div class="field"><label>Günlük kalori</label><input value="1600" type="number" /></div><div class="field"><label>Protein (g)</label><input value="120" type="number" /></div><div class="field"><label>Karbonhidrat (g)</label><input value="180" type="number" /></div><div class="field"><label>Yağ (g)</label><input value="55" type="number" /></div><button class="primary-btn" data-action="save-goal">Hedefi kaydet</button>`)}
function toast(message){const root=document.querySelector('#toast-root');root.innerHTML=`<div class="toast">${message}</div>`;setTimeout(()=>root.innerHTML='',2600)}
document.addEventListener('click',e=>{if(e.target.matches('[data-action="scan-result"]')){toast('Demo ürünü bulundu: Yulaflı bar');setTimeout(()=>{document.querySelector('#modal-root').innerHTML='';foodModal('Öğle')},500)} if(e.target.matches('[data-action="analyze-result"]')){toast('AI tabağını analiz ediyor…');setTimeout(()=>{document.querySelector('#modal-root').innerHTML='';modal('Analiz sonucu',`<div class="warning"><span>✦</span><div><strong>Yulaflı meyve kasesi</strong><p>Güven: %87 · Yaklaşık 310 kcal</p></div></div><div class="analytics-stats" style="margin:15px 0"><div class="stat-card"><span>Protein</span><strong>18g</strong></div><div class="stat-card"><span>Karbonhidrat</span><strong>42g</strong></div></div><button class="primary-btn" data-action="add-demo-food" data-meal="Öğle">Günlüğe ekle</button>`)},700)} if(e.target.matches('[data-action="generate-result"]')){toast('Tarifin hazırlanıyor…');setTimeout(()=>{document.querySelector('#modal-root').innerHTML='';modal('Tarif hazır',`<span class="sticker teal">✦ AI önerisi</span><h3 style="font-size:25px;margin:12px 0">Ispanaklı domates shakshuka</h3><p style="font-size:13px;line-height:1.45">Tek tavada hazırlanan, yoğun aromalı ve protein dostu bir akşam yemeği.</p><div class="recipe-meta" style="margin:16px 0"><span>⏱ 25 dk</span><span>♨ 420 kcal</span><span>🥚 27g protein</span></div><button class="primary-btn" data-action="save-recipe">Tarifi kaydet</button>`)},700)} });
document.addEventListener('click',e=>{if(!e.target.matches('[data-action="save-profile"],[data-action="save-allergens"],[data-action="save-goal"],[data-action="save-recipe"]'))return; if(e.target.dataset.action==='save-profile'){mutateRemote(API.profile,'PUT',{displayName:document.querySelector('#profile-name')?.value||'Melih Esen',weightKg:Number(document.querySelector('#profile-weight')?.value||75),heightCm:Number(document.querySelector('#profile-height')?.value||180),gender:null,birthDate:null}).then(ok=>{document.querySelector('#modal-root').innerHTML='';toast(ok?'Profil kaydedildi ✓':'Profil kaydedildi (demo) ✓');render()});return} document.querySelector('#modal-root').innerHTML='';toast('Değişiklikler kaydedildi ✓');render()});
document.addEventListener('click',async e=>{if(!e.target.matches('[data-action="firebase-login"],[data-action="firebase-register"],[data-action="firebase-reset"]')) return; const auth=await loadFirebase(); if(!auth){toast('Firebase config.js bilgileri henüz doldurulmadı.');return} const {signInWithEmailAndPassword,createUserWithEmailAndPassword,sendPasswordResetEmail}=await import('https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js'); const email=document.querySelector('#auth-email')?.value?.trim(); const password=document.querySelector('#auth-password')?.value; try { if(e.target.dataset.action==='firebase-login') await signInWithEmailAndPassword(auth,email,password); if(e.target.dataset.action==='firebase-register') await createUserWithEmailAndPassword(auth,email,password); if(e.target.dataset.action==='firebase-reset') await sendPasswordResetEmail(auth,email); document.querySelector('#modal-root').innerHTML='';toast('Firebase oturumu hazır ✓'); } catch(err){toast('Giriş işlemi tamamlanamadı. E-posta ve şifreni kontrol et.')} });
render();
