services:
  eatwell-postgres:
    image: postgres:16-alpine
    container_name: eatwell-backend-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: EatWellBackendDb
    ports:
      - "5434:5432"
    volumes:
      - eatwell_backend_postgres_data:/var/lib/postgresql/data

volumes:
  eatwell_backend_postgres_data:
