import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { colors, radius, spacing, typography } from '../../../theme';
import { useAddDailyLogItem } from '../../daily-log/hooks/useDailyLogMutations';
import { MealType } from '../../daily-log/types';
import { useFavorites, useRemoveFavorite } from '../hooks/useFavorites';
import { SavedFoodDto } from '../api/foods.service';
import { getLocalDateString } from '../../../utils/date';

export function FavoritesScreen() {
  const query = useFavorites(); const remove = useRemoveFavorite(); const date = getLocalDateString(); const addItem = useAddDailyLogItem(date); const [selected, setSelected] = useState<SavedFoodDto | null>(null); const [grams, setGrams] = useState('100'); const [meal, setMeal] = useState<MealType>('Ara Öğün');
  const add = () => { if (!selected) return; const quantity = Number(grams.replace(',', '.')); if (!Number.isFinite(quantity) || quantity <= 0) { Alert.alert('Gramaj gerekli', 'Geçerli bir gramaj girin.'); return; } addItem.mutate({ foodExternalId: selected.foodExternalId, foodName: selected.foodName, quantityGrams: quantity, mealType: meal, logDate: date, caloriesPer100Grams: selected.caloriesPer100Grams ?? null, proteinPer100Grams: selected.proteinPer100Grams ?? null, carbohydratesPer100Grams: selected.carbohydratesPer100Grams ?? null, fatPer100Grams: selected.fatPer100Grams ?? null, brand: selected.brand ?? null, barcode: selected.barcode ?? null }, { onSuccess: () => { setSelected(null); Alert.alert('Eklendi', 'Ürün bugünkü loguna eklendi.'); } }); };
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>KAYITLILAR</Text><Text style={styles.title}>Favori gıdalar</Text><Text style={styles.subtitle}>Sık kullandığın ürünleri hızlıca bugüne ekle.</Text>{query.isLoading ? <Text style={styles.muted}>Favoriler yükleniyor…</Text> : null}{(query.data ?? []).map((food) => <View key={food.foodExternalId} style={styles.item}><View style={styles.copy}><Text style={styles.name}>{food.foodName}</Text><Text style={styles.meta}>{food.brand ?? 'Ürün'}{food.caloriesPer100Grams != null ? ` · ${Math.round(food.caloriesPer100Grams)} kcal / 100 g` : ''}</Text></View><Pressable style={styles.addButton} onPress={() => setSelected(food)}><Text style={styles.addText}>Ekle</Text></Pressable><Pressable onPress={() => remove.mutate(food.foodExternalId)}><Text style={styles.remove}>×</Text></Pressable></View>)}{!query.isLoading && (query.data ?? []).length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>Henüz favorin yok</Text><Text style={styles.muted}>Tara ekranındaki ürün sonuçlarından favorilere ekleyebilirsin.</Text></View> : null}{selected ? <View style={styles.editor}><Text style={styles.editorTitle}>{selected.foodName}</Text><Text style={styles.muted}>Bugüne ekle</Text><View style={styles.meals}>{(['Kahvaltı', 'Öğle', 'Akşam', 'Ara Öğün'] as MealType[]).map((item) => <Pressable key={item} style={[styles.chip, meal === item && styles.chipActive]} onPress={() => setMeal(item)}><Text style={[styles.chipText, meal === item && styles.chipTextActive]}>{item}</Text></Pressable>)}</View><TextInput value={grams} onChangeText={setGrams} keyboardType="decimal-pad" style={styles.input} placeholder="Gramaj (g)" placeholderTextColor={colors.textMuted} /><View style={styles.actions}><Pressable style={styles.cancel} onPress={() => setSelected(null)}><Text style={styles.cancelText}>Vazgeç</Text></Pressable><Pressable style={styles.confirm} onPress={add}><Text style={styles.confirmText}>Bugüne ekle</Text></Pressable></View></View> : null}</ScrollView>;
}

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: spacing.xl, paddingBottom: 120 }, eyebrow: { ...typography.label, color: colors.coral, letterSpacing: 1.4 }, title: { ...typography.title, color: colors.text, marginTop: 4 }, subtitle: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm, marginBottom: spacing.lg }, item: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.md, padding: spacing.md, marginBottom: spacing.sm }, copy: { flex: 1 }, name: { ...typography.heading, color: colors.text, fontSize: 15 }, meta: { ...typography.body, color: colors.textMuted, fontSize: 12, marginTop: 3 }, addButton: { backgroundColor: colors.coral, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 9 }, addText: { ...typography.label, color: colors.white }, remove: { color: colors.textMuted, fontSize: 24, marginLeft: spacing.sm }, muted: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm }, empty: { backgroundColor: colors.surface, borderRadius: radius.lg, padding: spacing.lg, borderWidth: 1, borderColor: colors.border }, emptyTitle: { ...typography.heading, color: colors.text }, editor: { backgroundColor: colors.surface, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.coral, padding: spacing.lg, marginTop: spacing.lg }, editorTitle: { ...typography.heading, color: colors.text }, meals: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, chip: { borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, paddingVertical: 9, paddingHorizontal: spacing.sm }, chipActive: { borderColor: colors.coral, backgroundColor: '#FFF0EC' }, chipText: { ...typography.label, color: colors.textMuted }, chipTextActive: { color: colors.coral }, input: { height: 52, borderRadius: radius.md, backgroundColor: colors.surfaceMuted, paddingHorizontal: spacing.md, color: colors.text, marginTop: spacing.md, fontSize: 17 }, actions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md }, cancel: { flex: 1, height: 50, borderWidth: 1, borderColor: colors.border, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center' }, cancelText: { ...typography.label, color: colors.text }, confirm: { flex: 1, height: 50, backgroundColor: colors.coral, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center' }, confirmText: { ...typography.label, color: colors.white } });
