services:
  eatwell-postgres:
    image: postgres:16-alpine
    container_name: eatwell-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: EatWellFeelWellDb
    ports:
      - "5432:5432"
    volumes:
      - eatwell_postgres_data:/var/lib/postgresql/data

volumes:
  eatwell_postgres_data:
