import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as ImagePicker from 'expo-image-picker';
import { colors, radius, spacing, typography } from '../../../theme';
import { useGenerateRecipe } from '../hooks/useGenerateRecipe';
import { useSaveRecipe } from '../hooks/useSavedRecipes';

export function RecipesScreen() { const [mode, setMode] = useState<'find' | 'create'>('find'); const [ingredient, setIngredient] = useState(''); const [ingredients, setIngredients] = useState<string[]>([]); const generate = useGenerateRecipe(); const save = useSaveRecipe();
  const add = () => { const value = ingredient.trim(); if (value && ingredients.length < 10) { setIngredients([...ingredients, value]); setIngredient(''); } };
  const photo = async () => { const response = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], base64: true, quality: 0.8 }); if (response.canceled || !response.assets[0].base64) return; const asset = response.assets[0]; generate.mutate({ ingredients: [], servings: 2, imageBase64: asset.base64 ?? undefined, mimeType: asset.mimeType ?? 'image/jpeg' }, { onError: () => Alert.alert('Tarif bulunamadı', 'Fotoğraf analiz edilemedi.') }); };
  const result = generate.data;
  return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text style={styles.eyebrow}>TARİFLER</Text><Text style={styles.title}>Ne hazırlayalım?</Text><View style={styles.tabs}><Pressable style={[styles.tab, mode === 'find' && styles.active]} onPress={() => setMode('find')}><Text style={styles.tabText}>Tarif Bul</Text></Pressable><Pressable style={[styles.tab, mode === 'create' && styles.active]} onPress={() => setMode('create')}><Text style={styles.tabText}>Tarif Oluştur</Text></Pressable></View>{mode === 'find' ? <View style={styles.card}><Text style={styles.cardTitle}>Fotoğraftan tarif bul</Text><Text style={styles.muted}>Bir yemek fotoğrafı yükleyin; malzemeleri ve hazırlanışını analiz edelim.</Text><Pressable style={styles.primary} onPress={() => void photo()} disabled={generate.isPending}><Text style={styles.primaryText}>{generate.isPending ? 'Analiz ediliyor…' : 'Fotoğraf yükle veya çek'}</Text></Pressable></View> : <View style={styles.card}><Text style={styles.cardTitle}>Malzemeler</Text><Text style={styles.muted}>En fazla 10 malzeme ekleyin.</Text><View style={styles.row}><TextInput value={ingredient} onChangeText={setIngredient} onSubmitEditing={add} placeholder="Malzeme ara veya yaz" placeholderTextColor={colors.textMuted} style={styles.input} /><Pressable style={styles.add} onPress={add}><Text style={styles.addText}>Ekle</Text></Pressable></View><View style={styles.chips}>{ingredients.map((item) => <Pressable key={item} onPress={() => setIngredients(ingredients.filter((entry) => entry !== item))} style={styles.chip}><Text style={styles.chipText}>{item} ×</Text></Pressable>)}</View><Pressable style={[styles.primary, ingredients.length === 0 && styles.disabled]} disabled={!ingredients.length || generate.isPending} onPress={() => generate.mutate({ ingredients, servings: 2 })}><Text style={styles.primaryText}>{generate.isPending ? 'Hazırlanıyor…' : 'Tarif oluştur'}</Text></Pressable></View>}{result ? <View style={styles.result}><Text style={styles.cardTitle}>{result.recipeName}</Text><Text style={styles.muted}>{result.description}</Text><Pressable style={styles.save} onPress={() => save.mutate(result)} disabled={save.isPending}><Text style={styles.saveText}>{save.isPending ? 'Kaydediliyor…' : '☆ Tariflerime kaydet'}</Text></Pressable><Text style={styles.meta}>{result.preparationMinutes + result.cookingMinutes} dakika · {result.servings} porsiyon</Text><Text style={styles.section}>Malzemeler</Text>{result.ingredients.map((item) => <Text key={item.name} style={styles.line}>• {item.name} {item.quantity}</Text>)}<Text style={styles.section}>Hazırlanışı</Text>{result.steps.map((step, index) => <Text key={`${index}-${step}`} style={styles.line}>{index + 1}. {step}</Text>)}{result.youtubeSearchUrl ? <Text style={styles.link}>YouTube tarif bağlantısı hazır</Text> : null}</View> : null}</ScrollView>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { padding: spacing.lg, paddingTop: spacing.xl, paddingBottom: 120 }, eyebrow: { ...typography.label, color: colors.coral, letterSpacing: 1.4 }, title: { ...typography.title, color: colors.text, marginTop: 4 }, tabs: { flexDirection: 'row', backgroundColor: colors.surfaceMuted, borderRadius: radius.pill, padding: 4, marginTop: spacing.xl }, tab: { flex: 1, paddingVertical: 12, alignItems: 'center', borderRadius: radius.pill }, active: { backgroundColor: colors.surface }, tabText: { ...typography.label, color: colors.text }, card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radius.lg, padding: spacing.lg, marginTop: spacing.lg }, cardTitle: { ...typography.heading, color: colors.text }, muted: { ...typography.body, color: colors.textMuted, marginTop: spacing.sm }, primary: { height: 52, borderRadius: radius.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.coral, marginTop: spacing.lg }, primaryText: { ...typography.label, color: colors.white }, row: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg }, input: { flex: 1, height: 50, paddingHorizontal: spacing.md, backgroundColor: colors.surfaceMuted, borderRadius: radius.md, color: colors.text }, add: { paddingHorizontal: spacing.md, borderRadius: radius.md, justifyContent: 'center', backgroundColor: colors.ink }, addText: { ...typography.label, color: colors.white }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.md }, chip: { backgroundColor: colors.surfaceMuted, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 9 }, chipText: { ...typography.label, color: colors.text }, disabled: { opacity: 0.45 }, result: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.coral, borderRadius: radius.lg, padding: spacing.lg, marginTop: spacing.lg }, save: { alignSelf: 'flex-start', borderWidth: 1, borderColor: colors.coral, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 9, marginTop: spacing.md }, saveText: { ...typography.label, color: colors.coral }, meta: { ...typography.label, color: colors.coral, marginTop: spacing.md }, section: { ...typography.heading, color: colors.text, marginTop: spacing.lg }, line: { ...typography.body, color: colors.text, marginTop: spacing.sm }, link: { ...typography.label, color: colors.cobalt, marginTop: spacing.lg } });
